[workspace]
authors = ["Diego Ferigo <dgferigo@gmail.com>"]
channels = ["conda-forge"]
name = "dotfiles"
platforms = ["linux-64"]
version = "0.1.0"

[tasks.lint]
cmd = "ruff check"

[tasks.check]
cmd = "pyright .local/bin/dotfiles tests/"

[tasks.test]
clean-env = true
cmd = "pytest"

[tasks.hooks]
cmd = "pre-commit run --all-files"

[tasks.toml]
cmd = "tombi format && tombi lint"

[tasks.md]
cmd = ["sh", "-c", "git ls-files '*.md' | xargs mdformat"]

[dependencies]
bash = "*"
coreutils = "*"
curl = "*"
findutils = "*"
git = "*"
gitpython = "*"
ipython = "*"
mdformat = "*"
mdformat-frontmatter = "*"
mdformat-gfm = "*"
mdformat-pyproject = "*"
pre-commit = "*"
pyright = "*"
pytest = "*"
rich = "*"
ruff = "*"
shellcheck = "*"
tombi = "*"
unzip = "*"
wget = "*"
which = "*"
