#!/bin/bash

# fzf
[[ -f /usr/share/bash-completion/completions/fzf ]] && source /usr/share/bash-completion/completions/fzf
[[ -f /usr/share/doc/fzf/examples/key-bindings.bash ]] && source /usr/share/doc/fzf/examples/key-bindings.bash
[[ -f $HOME/.local/share/bash-completion/key-bindings.bash ]] && source ~/.local/share/bash-completion/key-bindings.bash
[[ -f $HOME/.local/share/bash-completion/fzf.bash-completion/completion.bash ]] && source ~/.local/share/bash-completion/fzf.bash-completion/completion.bash

# fd
[[ -f $HOME/.local/share/bash-completion/fd.bash-completion ]] && source $HOME/.local/share/bash-completion/fd.bash-completion

# z
[[ -f ${DOTFILES_SHARE}/z/z.sh ]] && source ${DOTFILES_SHARE}/z/z.sh
