#!/bin/bash

export DOTFILES_SHARE=${DOTFILES_SHARE:-~/.dotfiles/share}
[[ -d ${DOTFILES_SHARE} ]] && export PATH=${DOTFILES_SHARE}:${PATH}

# Load dotfiles resources
for file in ~/.bashrc.d/* ; do

    if [[ $(basename $file) == "init" ]] ; then
        continue
    fi

    source "$file"
done
