#!/bin/bash

if [[ -n $(type -t starship) ]]; then

    eval "$(starship init bash)"

    # Do not turn the prompt character red when the previous command was
    # interrupted with Ctrl+C (SIGINT exits 130). starship reads the exit
    # status from STARSHIP_CMD_STATUS and, before drawing the prompt, runs the
    # function whose name is held in the starship_precmd_user_func variable, so
    # we use it to remap 130 to a success status.
    _starship_ignore_sigint() {
        if [[ ${STARSHIP_CMD_STATUS:-0} -eq 130 ]]; then
            STARSHIP_CMD_STATUS=0
            STARSHIP_PIPE_STATUS=(0)
        fi
    }
    starship_precmd_user_func="_starship_ignore_sigint"

else

    [[ -f /usr/lib/git-core/git-sh-prompt ]] && source /usr/lib/git-core/git-sh-prompt

    # Colors, colors, colors
    if [ $UID -ne 0 ]; then
        PS1='${debian_chroot:+($debian_chroot)}\[\e[36;1m\]\u\[\e[0m\]@\H:\[\e[30;1m\]\w\[\e[0m\]\[\e[00;36m\]$(__git_ps1 " (%s)")\[\e[36;1m\]>\[\e[0m\]\[\e[1m\] '
    else
        PS1='${debian_chroot:+($debian_chroot)}\[\e[31;1m\]\u\[\e[0m\]@\H:\[\e[30;1m\]\w\[\e[31;1m\]#\[\e[0m\]\[\e[1m\] '
    fi

    # Reset PS1 color before command's output
    trap 'echo -ne "\e[0m"' DEBUG

fi
