format = """\
[╭── ](bold white)$container$all[╰─](bold white)$character"""

[username]
show_always = true
style_user = "bold purple"
style_root = "bold red"
format = "[$user]($style) "

[character]
success_symbol = "[\uF0DA](bold green)"
error_symbol = "[\uF0DA](bold red)"

[[battery.display]]
threshold = 2
style = "bold red"

[conda]
format = "[$symbol$environment  ](green bold)"

[git_branch]
symbol = "\U000F062C "
style = "dimmed"

[git_status]
disabled=true

[gcloud]
disabled=true

[python]
detect_files = []
detect_extensions = []
detect_folders = []

[pixi]
symbol = "✨"
format = 'via [$symbol $environment]($style)'
detect_files = []
detect_extensions = []
detect_folders = []
show_default_environment = false

[container]
symbol = "🐳"
style = "fg:#1E90FF bold"
format = '[$symbol]($style) '
