[[battery.display]]
threshold = 2
style = "bold red"

[conda]
format = "[$symbol$environment  ](green bold)"

[git_status]
disabled=true

[pixi]
symbol = "✨"
format = 'via [$symbol $environment]($style)'

[container]
symbol = "🐳"
style = "fg:#1E90FF bold"
format = '[$symbol]($style) '
